#!/usr/bin/perl
# vg - Vi Grepped - Copyright 1999 by Joshua Uziel <juziel@home.com>
# This program is released under the GNU General Public License.
# vg - cgvg version 1.3
#
# Helper script to go with cg for opening a editor conveniently
# with the correct file and line as shown in cg's log.  Run this
# with a single numerical argument (ie. "vg 3") to edit the desired
# log entry.
#
# This script seems to work fine with a number of editors, including
# vi, vim, emacs, pico, joe, etc.  (Despite it's name.)

# File where the log is.
$LOGFILE = "$ENV{'HOME'}/.cglast";

# Default editor to use.
$EDITOR = "vim";

# Use the $EDITOR environment variable if it exists.
$EDITOR = $ENV{'EDITOR'} if ($ENV{'EDITOR'});

# We can't edit if the editor doesn't exist.
`which $EDITOR`;
$no_editor = $?;
die "Error: Editor $EDITOR isn't in your path.\n" if ($no_editor);

# We need one argument only, and it has to be a number.
die "Error: Single argument needed.\n" unless ($#ARGV == 0);

# Set it to $num and test that it is a number.
$num = $ARGV[0];

die "Error: Non-numerical argument.\n" 
	unless (($num =~ /\d+/) && ($num !~ /\D+/));

die "Error: $LOGFILE doesn't exist.\n" unless (-f $LOGFILE);

open (IN, "<$LOGFILE");

# Check if our current path is the path when the log was taken.  If so,
# then nullify $path, else set it to $path/ so we can use anywhere.
$PWD=`pwd`;
$path=(split(/=/, <IN>))[1];
if ($PWD eq $path) {
	$path="";
} else {
	chomp($path);
	$path="$path/";
}

# Find the line we want and open up vi to that line.
foreach $line (<IN>) {
	($this, $file, $line) = (split(/:/, $line))[0,1,2];

	# Change this to execute the editor.
	exec "$EDITOR +$line $path$file" if ($num == $this);
}

# If we're here, there was a problem.
die "Error: Numerical argument invalid.\n";
